---
antora:
  name: modules
  dir: www
  modules:
    - name: "module-01-introduction"
      label: "Introduction"
      solveButton: true
    - name: "module-02-container-repository"
      label: "Create Container Repository"
      solveButton: true
    - name: "module-03-activation-key"
      label: "Create Activation Key"
      solveButton: true
    - name: "module-04-register-host"
      label: "Register Image Mode Host"
      solveButton: true
    - name: "module-05-verify-host"
      label: "Verify Image Mode Host Details"
      solveButton: true
    - name: "module-06-update-image"
      label: "Update Container Image"
      solveButton: true
    - name: "module-07-push-image"
      label: "Push Container Image"
      solveButton: true
    - name: "module-08-image-label"
      label: "Obtain Container Image Label"
      solveButton: true
    - name: "module-09-remote-job"
      label: "Schedule Remote Job"
      solveButton: true

tabs:
  - name: "Satellite Web UI"
    url: https://satellite-${guid}.${domain}/
  - name: "satellite.lab terminal"
    url: /wetty_satellite/ssh/root
  - name: "rhel1.lab terminal"
    url: /wetty_rhel1/ssh/root
  - name: "rhel2.lab terminal"
    url: /wetty_rhel2/ssh/root
